database:
  path: "../../data/score.db"

features:
  target: "final_test"
  redundant_list:
    - "index"
    - "number_of_siblings"
    - "student_id"
    - "gender"
    - "n_male"
    - "n_female"
    - "age"
    - "bag_color"
  non_corr_list:
    - "direct_admission"
    - "CCA"
    - "learning_style"
    - "tuition"
    - "mode_of_transport"
  time_list:
    - "sleep_time"
    - "wake_time"
  corr_list:
    - "attendance_rate"
    - "hours_per_week"
    - "sleep_hours"

model:
  test_size: 0.2
  random_state: 42
  name_list: # Valid values are "Linear Regression/Random Forest/SVR/MLP Regression/Bayesian Ridge/XG Boost
    - "Linear Regression"
    - "Random Forest"
    - "SVR"
  num_jobs: 4 # 0 to n -> Use n number of CPUs, -1 -> Use all available CPUs

rand_forest:
  est_list: # 
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
  depth_list:
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30

svr:
  c_list:
    - 0.1
    - 1
    - 5
    - 10
    - 15
    - 20
  kernel_list:
    - "linear"
    - "rbf" # Radial basis function - Effective for non-linear
    - "sigmoid" # Similar to neural network

mlp:
  hidden_layer_sizes_list:
    - [50, 50]
    - [100, 50]
    - [100, 100]
  activation_list:
    - "relu" # 
    - "tanh" # 
  solver_list:
    - "adam"
    - "sgd"
  learning_rate_list:
    - "constant"
    - "adaptive"
  max_iter_list:
    - 500
    - 1000
    - 1500
    - 2000

bayes:
  max_iter_list:
    - 300
    - 500
    - 1000
    - 1200
    - 1500
  alpha_1:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  alpha_2:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  lambda_1:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  lambda_2:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001

xgb:
  n_est_list:
    - 100
    - 200
    - 300
    - 400
    - 500
  learning_rate_list:
    - 0.01
    - 0.05
    - 0.1
  max_depth_list:
    - 3
    - 5
    - 7
    - 10
  subsample_list:
    - 0.6
    - 0.8
    - 1.0
