database:
  path: "../../data/score.db"

features:
  target: "final_test"
  redundant_list:
    - "index"
    - "number_of_siblings"
    - "student_id"
    - "gender"
    - "n_male"
    - "n_female"
    - "age"
    - "bag_color"
  non_corr_list:
    - "direct_admission"
    - "CCA"
    - "learning_style"
    - "tuition"
    - "mode_of_transport"
  time_list:
    - "sleep_time"
    - "wake_time"
  corr_list:
    - "attendance_rate"
    - "hours_per_week"
    - "sleep_hours"

model:
  test_size: 0.2
  random_state: 42