database:
  path: "../../data/score.db"

features:
  target: "final_test"
  redundant_list:
    - "index"
    - "number_of_siblings"
    - "student_id"
    - "gender"
    - "n_male"
    - "n_female"
    - "age"
    - "bag_color"
  non_corr_list:
    - "direct_admission"
    - "CCA"
    - "learning_style"
    - "tuition"
    - "mode_of_transport"
  time_list:
    - "sleep_time"
    - "wake_time"
  corr_list:
    - "attendance_rate"
    - "hours_per_week"
    - "sleep_hours"

model:
  test_size: 0.2
  random_state: 42
  name_list: # Valid values are "Linear Regression/Random Forest/SVR/MLP Regression/Bayesian Ridge/XG Boost
    - "Linear Regression"
    - "Random Forest"
    - "SVR"
  num_jobs: 4 # 0 to n -> Use n number of CPUs, -1 -> Use all available CPUs

rand_forest:
  est_list:
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
  depth_list:
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30

svr:
  c_list:
    - 0.1
    - 1
    - 5
    - 10
    - 15
    - 20
  kernel_list:
    - "linear"
    - "rbf" # Radial basis function - Effective for non-linear
    - "sigmoid" # Similar to neural network
