database:
  path: "../../data/noshow.db"

features:
  target: "no_show"
  num_map:
    one: 1
    two: 2
  standard_list:
    - "no_show"
    - "arrival_day"
    - "checkout_day"
    - "num_adults"
    - "num_children"
    - "sgd_price"
  one_hot_list:
    - "branch"
    - "booking_month"
    - "arrival_month"
    - "checkout_month"
    - "country"
    - "first_time"
    - "room"
    - "platform"

model:
  test_size: 0.2
  random_state: 42
  name_list: # Valid values are "Linear Regression/Random Forest/SVR/MLP Regression/Bayesian Ridge/XG Boost
    - "Linear Regression"
    - "Random Forest"
    - "SVR"
  search_method: "grid" # Valid values are "grid/random"
  cv_num: 5 # Number of cross-validation folds
  scoring: "neg_mean_squared_error"
  num_jobs: -1 # 0 to n -> Use n number of CPUs, -1 -> Use all available CPUs

rand_forest:
  est_list: # 
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    - 300
    - 325
    - 350
    - 375
    - 400
  depth_list:
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    - 40

svr:
  c_list:
    - 0.1
    - 1
    - 5
    - 10
    - 15
    - 20
  kernel_list:
    - "linear"
    - "rbf" # Radial basis function - Effective for non-linear
    - "sigmoid" # Similar to neural network

mlp:
  hidden_layer_sizes_list:
    - [50, 50]
    - [100, 50]
    - [100, 100]
  activation_list:
    - "relu" # 
    - "tanh" # 
  solver_list:
    - "adam"
    - "sgd"
  learning_rate_list:
    - "constant"
    - "adaptive"
  max_iter_list:
    - 500
    - 1000
    - 1500
    - 2000

bayes:
  max_iter_list:
    - 300
    - 500
    - 1000
    - 1200
    - 1500
  alpha_1:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  alpha_2:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  lambda_1:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
  lambda_2:
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001

xgb:
  n_est_list:
    - 100
    - 200
    - 300
    - 400
    - 500
  learning_rate_list:
    - 0.01
    - 0.05
    - 0.1
  max_depth_list:
    - 3
    - 5
    - 7
    - 10
  subsample_list:
    - 0.6
    - 0.8
    - 1.0
